### ISSUE TITLE
How to configure soundManager to compile this in?

### ISSUE THREAD

**Issue by randy-girard** [aadsm/customExternalInterface#1]
I have been trying to compile soundManager with this addition, but am having difficulties. What are the steps involved to add this to soundManager?

Thanks

**Comment by aadsm** [comment]
I don't recall exactly what changes I did, it was 3 years ago.
However, you should be able to grab a version of soundManager with this addition here: http://unite.opera.com/application/162/

**Comment by randy-girard** [comment]
Thanks.

I was actually hoping to be able to compile the newer soundManager with this enhanced, but realized I needed to make some updates for AS3. I was able to finally compile it, however now soundManager complains that flash is blocked and wont load. It may be that I just didn't implement to new ExternalInterface correctly. Any insights or challenges you ran into with that?

**Comment by aadsm** [comment]
I do remember having problems like that at the beginning, it was just a bug in my implementation of ExternalInterface, it was not communicating back to the JS. I figured out what the problem was by debugging SM, it's a well written piece of code so it's easy to follow.

I'm not familiar with AS (any version), I was asked to make soundManager work on the Wii so I just learned the minimum of AS2 at the time to implement this.
I was never into flash development, so I can't help you much on that field, sorry.
